# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# --- COMMON GRADLE START ---
# Mod Properties
mod_version=1.1.3
# Minecraft Versions
# Minecraft Versions
minecraft_version=1.20.4
neo_version=20.4.223
# mapping_version=2023.07.30
# mapping_channel=parchment
# Unchanging Mod info
mod_website_link=https://www.curseforge.com/minecraft/mc-mods/the-harvest
mod_issues_link=https://github.com/RobertSkalko/the_harvest
mod_display_name=The Harvest
mod_archive_name=The-Harvest
mod_id=the_harvest
# Publishing
curse_id=1201731
modrinth_id=sV6ykEOL
release_type=release
maven_group=com.robertx22
# Dependencies
exile_library_version=2.1.5
curios_version=7.4.3+1.20.4
jei_version=17.3.1.5
wiki_toolkit_version=0.2.4
publish_plugin_version=0.8.3
# --- COMMON GRADLE END ---
orbs_of_crafting_version=1.0.3