modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/RobertSkalko/Mine-And-Slash-Rework/issues"

[[mods]]
modId="mns_cobblemon"
version="${mod_version}"
displayName="Mine and Slash Cobblemon Compat"
authors="${mod_author}"
description='''Mine and Slash compatibility with Cobblemon.'''

[[dependencies.mns_cobblemon]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

[[dependencies.mns_cobblemon]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.mns_cobblemon]]
modId="mmorpg"
type="required"
versionRange="${mod_version}"
ordering="NONE"
side="BOTH"

[[dependencies.mns_cobblemon]]
modId="cobblemon"
type="required"
versionRange="[1.5,)"
ordering="NONE"
side="BOTH"
