modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/RobertSkalko/Mine-And-Slash-Rework/issues"

[[mods]]
modId="mns_minecolonies"
version="${mod_version}"
displayName="${mod_display_name}"
authors="${mod_author}"
description='''Mine and Slash compatibility with MineColonies.'''

[[dependencies.mns_minecolonies]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

[[dependencies.mns_minecolonies]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.mns_minecolonies]]
modId="mmorpg"
type="required"
versionRange="${mod_version}"
ordering="NONE"
side="BOTH"

[[dependencies.mns_minecolonies]]
modId="minecolonies"
type="required"
versionRange="[1.1.1213-1.21.1-snapshot,)"
ordering="NONE"
side="BOTH"
