# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
#allow gradle to cache the build
org.gradle.caching=true
# --- COMMON GRADLE START ---
# Mod Properties
mod_version=6.3.14
description = Turns Minecraft into a hack and slash RPG!


# Minecraft Versions
# Minecraft Versions
minecraft_version=1.20.4
neo_version=20.4.223
mod_author = mcrobertx22

#Parchment
parchment_minecraft=1.20.4
parchment_version=2024.04.14

# Unchanging Mod info
mod_website_link=https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded
mod_issues_link=https://github.com/RobertSkalko/Mine-And-Slash-Rework/issues
mod_display_name=Mine and Slash
mod_archive_name=Mine_and_Slash
mod_id=mmorpg

# Publishing
curse_id=306575
modrinth_id=oifKCkhG
release_type=release
group=com.robertx22
maven_group = com.robertx22

exile_library_version=2.1.5
curios_version=7.4.3+1.20.4
jei_version=17.3.1.5
wiki_toolkit_version=0.2.4
publish_plugin_version=0.8.3
player_animator_version=1.0.2-rc1+1.20.4
dungeon_realm_version=1.1.7
the_harvest_version=1.1.3
ancient_obelisks_version=1.2.3
dungeon_realm_project=1200770
dungeon_realm_file=7167022
ancient_obelisks_project=1186288
ancient_obelisks_file=6814709