plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev'
    id "me.modmuss50.mod-publish-plugin"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${mod_archive_name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '.cache/**'
}

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    compileOnly "net.neoforged:neoforge:${neo_version}"
    
    // MineColonies Dependency (CurseMaven)
    // Project ID: 245506, File ID: 7384176 (1.21.1 Release as of Dec 2025)
    implementation files("../libs/blockui-1.0.205-1.21.1.jar")
    implementation files("../libs/domum-ornamentum-1.0.223-snapshot-main.jar")
    implementation files("../libs/minecolonies-1.1.1242-1.21.1-snapshot.jar")
    implementation files("../libs/structurize-1.0.802-1.21.1-snapshot.jar")

    implementation project(':mine_and_slash') // Depends on the main mod
    implementation project(':Library-of-Exile-Rework') // Transitive dependency often needed
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : mod_archive_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    int pack_format = getPackFormat()
    var expandProps = [
            "mod_version"     : mod_version,
            "mod_id"          : mod_id,
            "mod_issues_link" : mod_issues_link,
            "mod_website_link": mod_website_link,
            "mod_display_name": mod_display_name,
            "mod_author": mod_author,
            "neo_version":neo_version,
            'group'                        : project.group,
            'minecraft_version'            : minecraft_version,
            'mod_name'                     : mod_archive_name,
            "pack_format"               : pack_format
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

int getPackFormat() {
    return 48 // 1.21.1
}
