plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev'
    id "me.modmuss50.mod-publish-plugin"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${mod_archive_name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

minecraft {
    // accessTransformers {
    //    file('src/main/resources/META-INF/accesstransformer.cfg')
    // }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '.cache/**'
}

repositories {
    maven { url = "https://maven.theillusivec4.top/" } // curios
    maven { url = "https://maven.kosmx.dev/" } // player animations
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev/"
        content {
            includeGroup "mezz.jei"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    compileOnly "net.neoforged:neoforge:${neo_version}"

    compileOnly ("top.theillusivec4.curios:curios-neoforge:${curios_version}:api")
    runtimeOnly ("top.theillusivec4.curios:curios-neoforge:${curios_version}")
    
    // JUnit 5 for testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.8.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.8.0'
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : mod_archive_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
        showStandardStreams = false
    }
}

processResources {
    int pack_format = getPackFormat()
    var expandProps = [
            "mod_version"     : mod_version,
            "mod_id"          : mod_id,
            "mod_issues_link" : mod_issues_link,
            "mod_website_link": mod_website_link,
            "mod_display_name": mod_display_name,
            "mod_author": mod_author,
            "neo_version":neo_version,
            'group'                        : project.group,
            'minecraft_version'            : minecraft_version,
            'mod_name'                     : mod_archive_name,
            "pack_format"               : pack_format
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

int getPackFormat() {
    return 48 // 1.21.1
}

publishMods {
    file = jar.archiveFile
    changelog = file("CHANGELOG.txt").text
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.add("neoforge")
    displayName = "${mod_archive_name}-${minecraft_version}-v${mod_version}"

    curseforge {
        accessToken = file("key.properties").exists() ? file("key.properties").text : ""
        projectId = "${curse_id}"
        minecraftVersions.add("${minecraft_version}")
        minecraftVersions.add("1.20")
    }

    modrinth {
        accessToken = file("modrinth_key.properties").exists() ? file("modrinth_key.properties").text : ""
        projectId = "${modrinth_id}"
        minecraftVersions.add("${minecraft_version}")
        minecraftVersions.add("1.20")
    }
}
