# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Dependencies
# --- COMMON GRADLE START ---
# Mod Properties
mod_version=2.1.5

#Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Minecraft Versions
# Minecraft Versions
minecraft_version=1.21.1
neo_version=21.1.77
mod_author = mcrobertx22

# Unchanging Mod info
mod_website_link=https://www.curseforge.com/minecraft/mc-mods/library-of-exile
mod_issues_link=https://github.com/RobertSkalko/Library-of-Exile-Rework
mod_display_name=Library of Exile
mod_archive_name=Library_of_Exile
mod_id=library_of_exile

# Publishing
curse_id=398780
modrinth_id=p87a38Zl
release_type=release
group=com.robertx22
maven_group = com.robertx22

# Dependencies
exile_library_version=1.5.5
curios_version=9.1.0+1.21.1
jei_version=19.21.0.247
wiki_toolkit_version=0.2.4
publish_plugin_version=0.8.3
# --- COMMON GRADLE END ---